Repository esm-tools/esm_tools, pull requests merged in 2022-06, with the labels that each got.

#692 fix/echam switches and version checks
  configs/components/echam/echam.yaml
  configs/components/jsbach/jsbach.yaml
  namelists/echam/6.3.05p2-wiso/PI-CTRL/namelist.echam
  setup.cfg
  setup.py
  src/esm_archiving/__init__.py
  src/esm_calendar/__init__.py
  src/esm_cleanup/__init__.py
  src/esm_database/__init__.py
  src/esm_environment/__init__.py
  src/esm_master/__init__.py
  src/esm_motd/__init__.py
  src/esm_parser/__init__.py
  src/esm_parser/esm_parser.py
  src/esm_plugin_manager/__init__.py
  src/esm_profile/__init__.py
  src/esm_runscripts/__init__.py
  src/esm_tests/__init__.py
  src/esm_tests/tests.py
  src/esm_tools/__init__.py
  src/esm_utilities/__init__.py
Labels: bug, echam

#586 Update installation.rst
  docs/installation.rst
Labels: documentation, Hackathon

#703 Fix/esm tests group output GitHub
  setup.cfg
  setup.py
  src/esm_archiving/__init__.py
  src/esm_calendar/__init__.py
  src/esm_cleanup/__init__.py
  src/esm_database/__init__.py
  src/esm_environment/__init__.py
  src/esm_master/__init__.py
  src/esm_motd/__init__.py
  src/esm_parser/__init__.py
  src/esm_plugin_manager/__init__.py
  src/esm_profile/__init__.py
  src/esm_runscripts/__init__.py
  src/esm_tests/__init__.py
  src/esm_tests/info.py
  src/esm_tests/tests.py
  src/esm_tools/__init__.py
  src/esm_utilities/__init__.py
Labels: continuous integration

#604 CI: Fix for PyPI Publication
  .github/workflows/esm_tools_publish.yml
  .github/workflows/pre-merge_actions.yml
  .gitignore
Labels: continuous integration, Hackathon

#704 fixes wrong oasis branch name
  configs/components/oasis3mct/oasis3mct.yaml
  setup.cfg
  setup.py
  src/esm_archiving/__init__.py
  src/esm_calendar/__init__.py
  src/esm_cleanup/__init__.py
  src/esm_database/__init__.py
  src/esm_environment/__init__.py
  src/esm_master/__init__.py
  src/esm_motd/__init__.py
  src/esm_parser/__init__.py
  src/esm_plugin_manager/__init__.py
  src/esm_profile/__init__.py
  src/esm_runscripts/__init__.py
  src/esm_tests/__init__.py
  src/esm_tools/__init__.py
  src/esm_utilities/__init__.py
Labels: oasis

#708 Remove develop merge in CI
  .github/workflows/pre-merge_actions.yml
Labels: continuous integration
