Repository esm-tools/esm_tools, pull requests merged in 2022-08, with the labels that each got.

#754 clean: remove all references to six
  setup.cfg
  setup.py
  src/esm_archiving/__init__.py
  src/esm_calendar/__init__.py
  src/esm_cleanup/__init__.py
  src/esm_database/__init__.py
  src/esm_environment/__init__.py
  src/esm_master/__init__.py
  src/esm_motd/__init__.py
  src/esm_parser/__init__.py
  src/esm_parser/esm_parser.py
  src/esm_plugin_manager/__init__.py
  src/esm_profile/__init__.py
  src/esm_runscripts/__init__.py
  src/esm_runscripts/backup/old_stuff.py
  src/esm_runscripts/backup/sadfile.py
  src/esm_runscripts/batch_system.py
  src/esm_runscripts/compute.py
  src/esm_runscripts/filelists.py
  src/esm_runscripts/logfiles.py
  src/esm_runscripts/namelists.py
  src/esm_runscripts/prepcompute.py
  src/esm_runscripts/prepexp.py
  src/esm_runscripts/resubmit.py
  src/esm_tests/__init__.py
  src/esm_tools/__init__.py
  src/esm_utilities/__init__.py
Labels: dependencies, cleanup

#791 sprint/filedicts/default names and allow missing path_in_computer
  src/esm_runscripts/filedicts.py
Labels: Sprint

#788 Datestamps
  src/esm_runscripts/filedicts.py
  tests/test_esm_runscripts/test_filedicts.py
Labels: cleanup, Sprint

#796 create subfolders in target names
  src/esm_runscripts/filedicts.py
  tests/test_esm_runscripts/test_filedicts.py
Labels: Sprint

#797 adds logger. adds __str__
  src/esm_runscripts/filedicts.py
Labels: Sprint

#798 fixes most of the mypy warnings / errors
  src/esm_runscripts/filedicts.py
Labels: Sprint

#803 fix: circumvent the vcs check
  setup.cfg
  setup.py
  src/esm_archiving/__init__.py
  src/esm_calendar/__init__.py
  src/esm_cleanup/__init__.py
  src/esm_database/__init__.py
  src/esm_environment/__init__.py
  src/esm_master/__init__.py
  src/esm_motd/__init__.py
  src/esm_parser/__init__.py
  src/esm_plugin_manager/__init__.py
  src/esm_profile/__init__.py
  src/esm_runscripts/__init__.py
  src/esm_runscripts/prepare.py
  src/esm_tests/__init__.py
  src/esm_tools/__init__.py
  src/esm_utilities/__init__.py
Labels: bug
