Repository esm-tools/esm_tools, pull requests merged in 2022-07, with the labels that each got.

#712 feat/yaml warning and error
  configs/esm_software/esm_runscripts/esm_plugins.yaml
  configs/esm_software/esm_runscripts/esm_runscripts.yaml
  docs/yaml.rst
  setup.cfg
  setup.py
  src/esm_archiving/__init__.py
  src/esm_calendar/__init__.py
  src/esm_cleanup/__init__.py
  src/esm_database/__init__.py
  src/esm_environment/__init__.py
  src/esm_master/__init__.py
  src/esm_motd/__init__.py
  src/esm_motd/esm_motd.py
  src/esm_parser/__init__.py
  src/esm_plugin_manager/__init__.py
  src/esm_profile/__init__.py
  src/esm_runscripts/__init__.py
  src/esm_runscripts/batch_system.py
  src/esm_runscripts/cli.py
  src/esm_runscripts/compute.py
  src/esm_runscripts/config_initialization.py
  src/esm_runscripts/prepare.py
  src/esm_runscripts/prepexp.py
  src/esm_runscripts/prev_run.py
  src/esm_tests/__init__.py
  src/esm_tools/__init__.py
  src/esm_utilities/__init__.py
  src/esm_utilities/utils.py
Labels: enhancement, error handling

#725 trying to fix the inclusion of the oasis_rmp_rst_to_input.py into the…
  configs/setups/awicm3/awicm3.yaml
  setup.cfg
  setup.py
  src/esm_archiving/__init__.py
  src/esm_calendar/__init__.py
  src/esm_cleanup/__init__.py
  src/esm_database/__init__.py
  src/esm_environment/__init__.py
  src/esm_master/__init__.py
  src/esm_motd/__init__.py
  src/esm_parser/__init__.py
  src/esm_plugin_manager/__init__.py
  src/esm_profile/__init__.py
  src/esm_runscripts/__init__.py
  src/esm_tests/__init__.py
  src/esm_tools/__init__.py
  src/esm_utilities/__init__.py
Labels: bug

#733 Docs for Usual Namelists
  docs/recipes/modify_namelists.rst
Labels: documentation

#661 adding HR mesh for fesom2
  configs/components/fesom/fesom-2.0.yaml
  namelists/fesom2/2.0/awicm3/HR/namelist.config
  namelists/fesom2/2.0/awicm3/HR/namelist.cvmix
  namelists/fesom2/2.0/awicm3/HR/namelist.forcing
  namelists/fesom2/2.0/awicm3/HR/namelist.ice
  namelists/fesom2/2.0/awicm3/HR/namelist.icepack
  namelists/fesom2/2.0/awicm3/HR/namelist.io
  namelists/fesom2/2.0/awicm3/HR/namelist.oce
  setup.cfg
  setup.py
  src/esm_archiving/__init__.py
  src/esm_calendar/__init__.py
  src/esm_cleanup/__init__.py
  src/esm_database/__init__.py
  src/esm_environment/__init__.py
  src/esm_master/__init__.py
  src/esm_motd/__init__.py
  src/esm_parser/__init__.py
  src/esm_plugin_manager/__init__.py
  src/esm_profile/__init__.py
  src/esm_runscripts/__init__.py
  src/esm_tests/__init__.py
  src/esm_tools/__init__.py
  src/esm_utilities/__init__.py
Labels: fesom
