Repository esm-tools/esm_tools, pull requests merged in 2023-11, with the labels that each got.

#1089 Update esm_tools_actions_novm.yml
  .github/workflows/esm_tools_actions_novm.yml
Labels: bug, continuous integration

#1094 Adding new OASIS coupling method gauswgt_glo for awicm3.
  configs/setups/awicm3/awicm3.yaml
  setup.cfg
  setup.py
  src/esm_archiving/__init__.py
  src/esm_calendar/__init__.py
  src/esm_cleanup/__init__.py
  src/esm_database/__init__.py
  src/esm_environment/__init__.py
  src/esm_master/__init__.py
  src/esm_motd/__init__.py
  src/esm_parser/__init__.py
  src/esm_plugin_manager/__init__.py
  src/esm_profile/__init__.py
  src/esm_runscripts/__init__.py
  src/esm_tests/__init__.py
  src/esm_tools/__init__.py
  src/esm_utilities/__init__.py
Labels: enhancement, oasis, awicm

#1040 fix orbital forcing for echam when the radctl namelist is empty
  setup.cfg
  setup.py
  src/esm_archiving/__init__.py
  src/esm_calendar/__init__.py
  src/esm_cleanup/__init__.py
  src/esm_database/__init__.py
  src/esm_environment/__init__.py
  src/esm_master/__init__.py
  src/esm_motd/__init__.py
  src/esm_parser/__init__.py
  src/esm_plugin_manager/__init__.py
  src/esm_profile/__init__.py
  src/esm_runscripts/__init__.py
  src/esm_runscripts/namelists.py
  src/esm_tests/__init__.py
  src/esm_tools/__init__.py
  src/esm_utilities/__init__.py
Labels: bug

#1100 Added package graphviz to rtd config file.
  .readthedocs.yml
Labels: bug, documentation

#1087 Fix/documentation installation
  CONTRIBUTING.rst
  docs/before_you_continue.rst
  docs/conf.py
  docs/esm_tools.rst
  docs/esm_versions.rst
  docs/get_esm-tools.rst
  docs/howtocite.rst
  docs/index.rst
  docs/installation.rst
  docs/introduction.rst
  docs/ten_steps.rst
  docs/yaml.rst
Labels: documentation
